#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
NC="\033[0m"

gtm() {
    echo -e "${CYAN}"
    echo "██╗██████╗░██╗░░██╗██╗░░░██╗███╗░░██╗████████╗"
    echo "██║██╔══██╗██║░░██║██║░░░██║████╗░██║╚══██╔══╝"
    echo "██║██████╔╝███████║██║░░░██║██╔██╗██║░░░██║░░░"
    echo "██║██╔═══╝░██╔══██║██║░░░██║██║╚████║░░░██║░░░"
    echo "██║██║░░░░░██║░░██║╚██████╔╝██║░╚███║░░░██║░░░"
    echo "╚═╝╚═╝░░░░░╚═╝░░╚═╝░╚═════╝░╚═╝░░╚══╝░░░╚═╝░░░"
    echo "${RED}MODIFIED BY ${YELLOW}NOTE"
    echo -e "${NC}"
    while true; do
        if curl -s -D- http://google.com -x "google.com:80" | grep -q "msisdn"; then
            echo -e "\\r\033[1;32mYou have found MAGIC SHIT ${GREEN}✓\033[0m\n"
            break
        else
            sleep 0.000001
            echo -ne "\\r\033[1;33mSearching for magic IP \033[1;34m${NC}[ ${RED}. ${NC}]"
            sleep 0.000001
            echo -ne "\\r\033[1;33mSearching for magic IP \033[1;34m${NC}[ ${RED}.. ${NC}]"
            sleep 0.000001
            echo -ne "\\r\033[1;33mSearching for magic IP \033[1;34m${NC}[ ${RED}... ${NC}]"
            sleep 0.000001
            echo -ne "\\r\033[1;33mSearching for magic IP \033[1;34m${NC}[ ${RED}.... ${NC}]"
            
        fi
    done
}
